In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
LEARNING_RATE = 0.45

In [3]:
def step(x):
    if (x > 0):
        return 1
    else:
        return -1;

In [4]:
INPUTS = np.array([[-1,-1,1],
                   [-1,1,1],
                   [1,-1,1],
                   [1,1,1] ])         
OUTPUTS = np.array([[-1,1,1,1]]).T

array([[-1, -1,  1],
       [-1,  1,  1],
       [ 1, -1,  1],
       [ 1,  1,  1]])

In [6]:
OUTPUTS

array([[-1],
       [ 1],
       [ 1],
       [ 1]])

In [8]:
np.random.seed(1)

In [9]:
WEIGHTS = 2*np.random.random((3,1)) - 1

In [10]:
WEIGHTS

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [11]:
errors=[]

In [22]:
# Training loop
for iter in range(100):

    for input_item,desired in zip(INPUTS, OUTPUTS):
        
        ADALINE_OUTPUT = (input_item[0]*WEIGHTS[0]) + (input_item[1]*WEIGHTS[1]) + (input_item[2]*WEIGHTS[2])

        # Run ADALINE_OUTPUT through the step function
        ADALINE_OUTPUT = step(ADALINE_OUTPUT)

        # Calculate the ERROR generated
        ERROR = desired - ADALINE_OUTPUT
        
        # Store the ERROR
        errors.append(ERROR)
        
        # Update the weights
        WEIGHTS[0] = WEIGHTS[0] + LEARNING_RATE * ERROR * input_item[0]
        WEIGHTS[1] = WEIGHTS[1] + LEARNING_RATE * ERROR * input_item[1]
        WEIGHTS[2] = WEIGHTS[2] + LEARNING_RATE * ERROR * input_item[2]
    
    



In [15]:
WEIGHTS

array([[0.73404401],
       [1.34064899],
       [1.70022875]])

In [23]:
for input_item,desired in zip(INPUTS, OUTPUTS):

    ADALINE_OUTPUT = (input_item[0]*WEIGHTS[0]) + (input_item[1]*WEIGHTS[1]) + (input_item[2]*WEIGHTS[2])
    ADALINE_OUTPUT = step(ADALINE_OUTPUT)

    print("Actual ", ADALINE_OUTPUT, "Desired ", desired)



Actual  -1 Desired  [-1]
Actual  1 Desired  [1]
Actual  1 Desired  [1]
Actual  1 Desired  [1]
